In [2]:
import dgl
import torch
import numpy as np

/home/bear/miniconda3/envs/dgl_v09/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
low = 0
high = 100000
size = (10000,)  # 生成一个包含5个随机整数的序列
r_integers = torch.randint(low, high, size)

low = 0
high = 4
r_partition = torch.randint(low, high, size)

low = 0
high = 3
r_layer = torch.randint(low, high, size)

In [ ]:
rted_tensor, indices = torch.sort(r_integers, descending=True)
print(rted_tensor) # 值
print(indices) # 索引位置
               # 抽取GID

# 首先获得子图节点(GID)，并抽取出对应的特征，以及特征对应的重要度值
# 按照重要度对节点进行排序，拿到对应索引，随后映射回GID(GID排序)
# 利用索引重排特征，利用排序后GID生成LID(此时LID与特征依然对应)，随后对子图进行id重排
# 生成CSR格式数据


In [16]:
low = 0
high = 100
size = (10,)  # 生成一个包含5个随机整数的序列
r_GID = torch.randint(low, high, size)
r_GID

tensor([12, 10, 19, 37,  6, 32, 90, 44, 37, 77])

In [17]:
low = 0
high = 100
size = (10,)  # 生成一个包含5个随机整数的序列
r_value = torch.randint(low, high, size)
r_value

tensor([58, 15, 42, 63, 47, 85, 69, 19, 14, 48])

In [18]:
feat = r_GID.repeat_interleave(4)
feat = feat.reshape(-1,4)
feat

tensor([[12, 12, 12, 12],
        [10, 10, 10, 10],
        [19, 19, 19, 19],
        [37, 37, 37, 37],
        [ 6,  6,  6,  6],
        [32, 32, 32, 32],
        [90, 90, 90, 90],
        [44, 44, 44, 44],
        [37, 37, 37, 37],
        [77, 77, 77, 77]])

In [19]:
rted_tensor, indices = torch.sort(r_value, descending=True)
indices

tensor([5, 6, 3, 0, 9, 4, 2, 7, 1, 8])

In [20]:
rted_tensor

tensor([85, 69, 63, 58, 48, 47, 42, 19, 15, 14])

In [21]:
sort_GID = r_GID[indices]
sort_GID

tensor([32, 90, 37, 12, 77,  6, 19, 44, 10, 37])

In [22]:
feat = feat[indices]
feat

tensor([[32, 32, 32, 32],
        [90, 90, 90, 90],
        [37, 37, 37, 37],
        [12, 12, 12, 12],
        [77, 77, 77, 77],
        [ 6,  6,  6,  6],
        [19, 19, 19, 19],
        [44, 44, 44, 44],
        [10, 10, 10, 10],
        [37, 37, 37, 37]])