In [2]:
import dgl
import torch
import numpy as np

/home/bear/miniconda3/envs/dgl_v09/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
low = 0
high = 100000
size = (10000,)  # 生成一个包含5个随机整数的序列
random_integers = torch.randint(low, high, size)

In [12]:
rted_tensor, indices = torch.sort(random_integers, descending=True)
print(rted_tensor) # 值
print(indices) # 索引位置
               # 抽取GID

# 首先获得子图节点(GID)，并抽取出对应的特征，以及特征对应的重要度值
# 按照重要度对节点进行排序，拿到对应索引，随后映射回GID(GID排序)
# 利用索引重排特征，利用排序后GID生成LID(此时LID与特征依然对应)，随后对子图进行id重排
# 生成CSR格式数据


tensor([99985, 99979, 99967,  ...,    36,    19,    13])
tensor([8134, 2859, 5463,  ..., 1874,  482, 2642])


In [7]:
nodeTable = torch.Tensor([0,0,1,0,0,0,0,0,0,0]).to(torch.int32).cuda()
src = torch.Tensor([0,2,4,5,2,4,5,2]).to(torch.int32).cuda()
dst = torch.Tensor([1,3,7,6,4,2,3,3]).to(torch.int32).cuda()
acc = False
print(nodeTable)
dgl.fastFindNeighbor(nodeTable,src,dst,accumulate = False,flag=2)
print(nodeTable)

tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], device='cuda:0', dtype=torch.int32)
tensor([0, 0, 1, 2, 2, 0, 0, 0, 0, 0], device='cuda:0', dtype=torch.int32)
