In [1]:
import dgl
import torch
import numpy as np

/home/bear/miniconda3/envs/dgl_v09/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [17]:
src = torch.tensor([0, 1, 3, 2, 4, 5, 0, 1, 6, 2, 3, 4, 6, 0, 1, 5, 2, 3, 4], dtype=torch.int32)
random_permutation = torch.randperm(src.size(0))
src = src[random_permutation]
src = src.cuda()
dst = torch.tensor([0, 1, 3, 2, 4, 5, 0, 1, 6, 2, 3, 4, 6, 0, 1, 5, 2, 3, 4], dtype=torch.int32).cuda()
inptr = torch.cat([torch.Tensor([0]).to(torch.int32).cuda(),torch.cumsum(torch.bincount(src), dim=0)]).to(torch.int32).cuda()
addr = inptr.clone()[:-1].cuda()
indice = torch.zeros_like(dst).to(torch.int32).cuda()

In [18]:
print(addr)
print(inptr)
print(indice)

tensor([ 0,  3,  6,  9, 12, 15, 17], device='cuda:0', dtype=torch.int32)
tensor([ 0,  3,  6,  9, 12, 15, 17, 19], device='cuda:0', dtype=torch.int32)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       device='cuda:0', dtype=torch.int32)


In [19]:
dgl.cooTocsr(inptr,indice,addr,src,dst)

In [20]:
print(indice)

tensor([0, 2, 4, 1, 6, 2, 5, 0, 3, 3, 3, 0, 1, 2, 6, 4, 1, 4, 5],
       device='cuda:0', dtype=torch.int32)
